name: readout # read by workflow
defaults:
  readout_cfg_uri: "file:/home/flp/readout.cfg"
  user: flp
control:
  mode: direct
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: readout
    type: push
    rateLogging: "1"
    addressing: ipc
    transport: shmem
properties: {}
command: 
  env:
    #- HOST={{ machine_id }}
    - HOST="test"
  shell: true
  user: "{{ user }}"
  arguments:
    - "{{ readout_cfg_uri }}"
  value: >-
    eval `aliswmod load Readout Control-OCCPlugin` &&
    readout.exe
